name: React Build & Deploy

on:
  push:
    branches:
      - main # main 브랜치에 push되면 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4 # 저장소 코드 가져오기

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Node.js 버전 설정

      - name: Install dependencies
        run: npm install # 프로젝트 의존성 설치

      - name: Build
        run: npm run build # React 프로젝트 빌드

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # AWS 리전 설정

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://seohyun2-bucket-339741260422-ap-northeast-2-an --delete
          # dist 폴더를 S3 버킷에 업로드
